# Generated by Django 4.2.6 on 2024-05-09 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii')),
                ('category_description', models.TextField(blank=True, max_length=200, verbose_name='Opis kategorii')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=100, unique=True, verbose_name='Nazwa testu')),
                ('test_duration', models.DurationField(default='00:00:00', help_text='Czas musi być zapisany w formacie HH:MM:SS', verbose_name='Czas trwania testu')),
                ('test_opening_date', models.DateField(verbose_name='Dzień otwarcia testu')),
                ('test_start_login_time', models.TimeField(help_text='Czas musi być zapisany w formacie HH:MM:SS', verbose_name='Godzina rozpoczęcia logowania do testu')),
                ('test_end_login_time', models.TimeField(help_text='Czas musi być zapisany w formacie HH:MM:SS', verbose_name='Godzina zakończenia logowania do testu')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='test_app.category', verbose_name='Kategoria testu')),
                ('test_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_creator', to=settings.AUTH_USER_MODEL, verbose_name='Osoba tworząca test')),
            ],
            options={
                'verbose_name_plural': 'Testy',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_uidb64', models.CharField(max_length=255)),
                ('team_member_client', models.CharField(max_length=1000)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_team_member', to='registration_app.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(verbose_name='Treść pytania')),
                ('question_attachment', models.FileField(blank=True, upload_to='question_attachments/', verbose_name='Załącznik dla pytania')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Test')),
            ],
            options={
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_test_result', models.CharField(max_length=25, verbose_name='Wynik')),
                ('competition_test_performer_duration_time', models.DurationField(default='00:00:00', verbose_name='Czas wykonania')),
                ('suspicious_actions', models.IntegerField(default=0, verbose_name='Podejrzane działania')),
                ('competition_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Nazwa testu')),
                ('competition_test_performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.teammember', verbose_name='Osoba zdająca test')),
            ],
            options={
                'verbose_name_plural': 'Wyniki',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField(verbose_name='Treść odpowiedzi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Odpowiedź jest poprawna')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.question', verbose_name='Pytanie')),
            ],
            options={
                'verbose_name_plural': 'Odpowiedzi',
            },
        ),
    ]
