# Generated by Django 4.2.6 on 2024-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='competition_test_performer_pass_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_passing_time',
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_test_performer_duration_time',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_duration',
            field=models.DurationField(default='00:00:00', verbose_name='Czas wykonywania testu'),
        ),
    ]
