# Generated by Django 4.2.6 on 2024-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_competition_competition_test_performer_pass_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_correct_answer',
            field=models.TextField(verbose_name='Poprawna odpowiedz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_incorrect_answers',
            field=models.ManyToManyField(blank=True, related_name='incorrect_answers', to='test_app.answer', verbose_name='Niepoprawne odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_questions',
            field=models.ManyToManyField(blank=True, related_name='test_questions', to='test_app.question'),
        ),
    ]
