# Generated by Django 4.2.6 on 2024-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_question_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='competition_test',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competition_test_performer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_incorrect_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_creator',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_questions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
