# Generated by Django 4.2.6 on 2024-03-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_alter_guardian_options_alter_highschool_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0005_remove_competition_competition_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=100, unique=True)),
                ('test_duration', models.DurationField(default='00:00')),
                ('test_opening_date', models.DateField()),
                ('test_start_login_time', models.TimeField()),
                ('test_end_login_time', models.TimeField()),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='test_app.category')),
                ('test_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_test_result', models.CharField()),
                ('competition_test_performer_duration_time', models.DurationField(default='00:00')),
                ('competition_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
                ('competition_test_performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.question')),
            ],
        ),
    ]
