# Generated by Django 4.2.6 on 2024-04-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_alter_guardian_options_alter_highschool_options_and_more'),
        ('test_app', '0008_question_question_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': 'Wyniki'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test', verbose_name='Nazwa testu'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_test_performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.teammember', verbose_name='Osoba zdająca test'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_test_performer_duration_time',
            field=models.DurationField(default='00:00:00', verbose_name='Czas wykonania'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_test_result',
            field=models.CharField(verbose_name='Wynik'),
        ),
        migrations.CreateModel(
            name='LoggenInTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_team_member', to='registration_app.teammember')),
            ],
        ),
    ]
