# Generated by Django 4.2.6 on 2024-04-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggenInTeamMember',
        ),
    ]
