# Generated by Django 4.2.6 on 2024-04-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_alter_guardian_options_alter_highschool_options_and_more'),
        ('test_app', '0010_delete_loggeninteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_uidb64', models.CharField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_team_member', to='registration_app.teammember')),
            ],
        ),
    ]
