# Generated by Django 4.2.6 on 2024-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_teammembertestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembertestsession',
            name='team_member_client',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
