# Generated by Django 4.2.6 on 2024-04-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_teammembertestsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembertestsession',
            unique_together=set(),
        ),
    ]
