# Generated by Django 4.2.6 on 2024-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_alter_teammembertestsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='suspicious_actions',
            field=models.IntegerField(default=0, verbose_name='Podejrzane działania'),
        ),
    ]
