# Generated by Django 4.2.6 on 2023-12-06 20:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_surname', models.CharField(max_length=255)),
                ('guardian_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True)),
                ('guardian_email', models.EmailField(max_length=254, unique=True)),
                ('guardian_clause', models.FileField(upload_to='clauses/')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('school_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True)),
                ('school_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('member_surname', models.CharField(blank=True, max_length=255)),
                ('member_clause', models.FileField(upload_to='clauses/')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='registration_app.teammember')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.guardian')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='registration_app.highschool')),
                ('second_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember')),
            ],
        ),
    ]
