# Generated by Django 4.2.6 on 2024-05-09 19:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Imie opiekuna')),
                ('guardian_surname', models.CharField(max_length=255, verbose_name='Nazwisko opiekuna')),
                ('guardian_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True, verbose_name='Telefon komórkowy opiekuna')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-mail opiekuna')),
                ('guardian_clause', models.FileField(upload_to='clauses/', verbose_name='Klauzula opiekuna')),
            ],
            options={
                'verbose_name_plural': 'Opiekunowie',
            },
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Pełna nazwa szkoły')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Nazwa w skrócie')),
                ('city', models.CharField(max_length=255, verbose_name='Miasto')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('school_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True, verbose_name='Telefon komórkowy szkoły')),
                ('school_email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail szkoły')),
            ],
            options={
                'verbose_name_plural': 'Szkoły',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255, verbose_name='Imie uczęstnika')),
                ('member_surname', models.CharField(max_length=255, verbose_name='Nazwisko uczęstnika')),
                ('member_clause', models.FileField(upload_to='clauses/', verbose_name='Klauzula uczęstnika')),
            ],
            options={
                'verbose_name_plural': 'Uczniowie',
            },
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Zespół aktywny')),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='registration_app.teammember', verbose_name='Pierwszy uczęstnik')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.guardian', verbose_name='Opiekun')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='registration_app.highschool', verbose_name='Nazwa szkoły')),
                ('second_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember', verbose_name='Drugi uczęstnik')),
            ],
            options={
                'verbose_name_plural': 'Zespoły szkolne',
            },
        ),
    ]
