# Generated by Django 4.2.6 on 2023-10-17 10:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PL', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('clause', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PL', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('clause', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.guardian')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.highschool')),
                ('members', models.ManyToManyField(to='registration_app.teammember')),
            ],
        ),
    ]
