# Generated by Django 4.2.6 on 2023-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='members',
            field=models.ManyToManyField(max_length=2, to='registration_app.teammember'),
        ),
    ]
