# Generated by Django 4.2.6 on 2023-12-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_schoolteam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_surname',
            field=models.CharField(max_length=255),
        ),
    ]
