# Generated by Django 4.2.6 on 2023-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_alter_schoolteam_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='members',
            field=models.ManyToManyField(to='registration_app.teammember'),
        ),
    ]
