# Generated by Django 4.2.6 on 2023-12-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_alter_highschool_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='second_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember'),
        ),
    ]
