# Generated by Django 4.2.6 on 2023-10-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_alter_schoolteam_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='clause',
            field=models.FileField(upload_to='clauses/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='clause',
            field=models.FileField(upload_to='clauses/'),
        ),
    ]
