# Generated by Django 4.2.6 on 2023-11-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_alter_guardian_clause_alter_teammember_clause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='email',
            new_name='guardian_email',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='mobile_phone',
            new_name='guardian_mobile_phone',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='name',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='surname',
            new_name='guardian_surname',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='email',
            new_name='school_email',
        ),
        migrations.RenameField(
            model_name='highschool',
            old_name='mobile_phone',
            new_name='school_mobile_phone',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='surname',
            new_name='member_surname',
        ),
    ]
