# Generated by Django 4.2.6 on 2023-12-23 14:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_alter_schoolteam_second_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='guardian_clause',
            field=models.FileField(upload_to='clauses/', verbose_name='Klauzula opiekuna'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='E-mail opiekuna'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True, verbose_name='Telefon komórkowy opiekuna'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_name',
            field=models.CharField(max_length=255, verbose_name='Imie opiekuna'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_surname',
            field=models.CharField(max_length=255, verbose_name='Nazwisko opiekuna'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Pełna nazwa szkoły'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='post_code',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail szkoły'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True, verbose_name='Telefon komórkowy szkoły'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa w skrócie'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_clause',
            field=models.FileField(upload_to='clauses/', verbose_name='Klauzula uczęstnika'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_name',
            field=models.CharField(max_length=255, verbose_name='Imie uczęstnika'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_surname',
            field=models.CharField(max_length=255, verbose_name='Nazwisko uczęstnika'),
        ),
    ]
