# Generated by Django 4.2.6 on 2023-11-05 09:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_rename_email_guardian_guardian_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='clause',
            field=models.FileField(blank=True, upload_to='clauses/'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True),
        ),
    ]
