# Generated by Django 4.2.6 on 2024-01-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0007_alter_schoolteam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='first_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='registration_app.teammember', verbose_name='Pierwszy uczęstnik'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.guardian', verbose_name='Opiekun'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='high_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='registration_app.highschool', verbose_name='Nazwa szkoły'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Zespół aktywny'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='second_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember', verbose_name='Drugi uczęstnik'),
        ),
    ]
