# Generated by Django 4.2.6 on 2024-01-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_alter_schoolteam_first_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name_plural': 'Opiekunowie'},
        ),
        migrations.AlterModelOptions(
            name='highschool',
            options={'verbose_name_plural': 'Szkoły'},
        ),
        migrations.AlterModelOptions(
            name='schoolteam',
            options={'verbose_name_plural': 'Zespoły szkolne'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': 'Uczniowie'},
        ),
    ]
