# Generated by Django 4.2.6 on 2023-11-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_alter_teammember_clause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='clause',
            new_name='guardian_clause',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='clause',
            new_name='member_clause',
        ),
    ]
