# Generated by Django 4.2.6 on 2023-11-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_rename_clause_guardian_guardian_clause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='high_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='registration_app.highschool'),
        ),
    ]
