# Generated by Django 4.2.6 on 2023-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0010_alter_schoolteam_high_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
