# Generated by Django 4.2.6 on 2023-11-07 07:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0012_alter_highschool_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='guardian_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='guardian_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL'),
        ),
    ]
