# Generated by Django 4.2.6 on 2023-11-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0014_alter_guardian_guardian_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='guardian_clause',
            field=models.FileField(upload_to='clauses/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_clause',
            field=models.FileField(upload_to='clauses/'),
        ),
    ]
