# Generated by Django 4.2.6 on 2023-11-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0015_alter_guardian_guardian_clause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolteam',
            name='members',
        ),
        migrations.AddField(
            model_name='schoolteam',
            name='first_member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='registration_app.teammember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolteam',
            name='second_member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember'),
            preserve_default=False,
        ),
    ]
