# Generated by Django 4.2.6 on 2023-11-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0016_remove_schoolteam_members_schoolteam_first_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='second_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='registration_app.teammember'),
        ),
    ]
