# Generated by Django 4.2.6 on 2024-05-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=9, verbose_name='Dzień rozpoczęcia rejestracji')),
                ('date_to', models.DateField(default=9, verbose_name='Dzień zakończenia rejestracji')),
            ],
            options={
                'verbose_name_plural': 'Otwarcia rejestracji',
            },
        ),
    ]
