# Generated by Django 4.2.6 on 2024-02-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenRegistration',
        ),
    ]
