# Generated by Django 4.2.6 on 2024-01-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenRegistrationModel',
            new_name='OpenRegistration',
        ),
    ]
