# Generated by Django 4.2.6 on 2024-02-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0002_delete_openregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=15)),
                ('time_from', models.TimeField(default=datetime.time(11, 7, 37, 302476))),
                ('date_to', models.DateField(default=15)),
                ('time_to', models.TimeField(default=datetime.time(11, 7, 37, 302476))),
            ],
            options={
                'verbose_name_plural': 'Otwarcia rejestracji',
            },
        ),
    ]
