# Generated by Django 4.2.6 on 2024-01-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_openregistrationmodel_openregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openregistration',
            options={'verbose_name_plural': 'Otwarcia rejestracji'},
        ),
    ]
