# Generated by Django 4.2.6 on 2024-02-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openregistration',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='openregistration',
            name='time_to',
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='date_from',
            field=models.DateField(default=15, verbose_name='Dzień rozpoczęcia rejestracji'),
        ),
    ]
