# Generated by Django 4.2.6 on 2024-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_openregistration_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openregistration',
            name='date_to',
            field=models.DateField(default=15, verbose_name='Dzień zakończenia rejestracji'),
        ),
    ]
