# Generated by Django 4.2.6 on 2024-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_openregistration_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openregistration',
            name='date_from',
            field=models.DateField(default=28, verbose_name='Dzień rozpoczęcia rejestracji'),
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='date_to',
            field=models.DateField(default=28, verbose_name='Dzień zakończenia rejestracji'),
        ),
    ]
