# Generated by Django 4.2.6 on 2024-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_openregistration_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openregistration',
            name='date_from',
            field=models.DateField(default=25, verbose_name='Dzień rozpoczęcia rejestracji'),
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='date_to',
            field=models.DateField(default=25, verbose_name='Dzień zakończenia rejestracji'),
        ),
    ]
