# Generated by Django 4.2.6 on 2024-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_openregistration_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openregistration',
            name='date_from',
            field=models.DateField(default=10, verbose_name='Dzień rozpoczęcia rejestracji'),
        ),
        migrations.AlterField(
            model_name='openregistration',
            name='date_to',
            field=models.DateField(default=10, verbose_name='Dzień zakończenia rejestracji'),
        ),
    ]
